/**
 * Exercise artwork lookup.
 *
 * The art is a small set of line-art frames per movement, bundled as path data in
 * `src/data/exerciseArt.generated.ts` (generated by `scripts/build-exercise-art.mjs`
 * from bryllim/workout-guide, CC BY-SA 4.0, upstream Everkinetic — see NOTICE).
 *
 * Coverage is deliberately partial. A match is only emitted when the artwork
 * genuinely depicts the same movement: this is a lifting app, and showing a back
 * squat on a Hack Squat is worse than showing nothing. Everything unmatched falls
 * back to the initials monogram, which is the app's normal empty state.
 *
 * This module is the ONLY importer of the generated file, so regenerating the art
 * (or dropping it entirely) never reaches a component.
 */
import { ART_BY_EXERCISE_ID, ART_FRAMES, ART_VIEWBOX } from '../data/exerciseArt.generated';

export type ExerciseArt = {
  /** Shared viewBox for every frame, e.g. `0 0 512 512`. */
  viewBox: string;
  /** `d` attributes, in order — frame 0 is the start position. */
  frames: readonly string[];
};

/**
 * Artwork for a catalog exercise, or null when we have none for it (the common
 * case — callers must render their own fallback).
 */
export function exerciseArt(exerciseId: string | null | undefined): ExerciseArt | null {
  if (!exerciseId) return null;
  const slug = ART_BY_EXERCISE_ID[exerciseId];
  if (!slug) return null;
  const frames = ART_FRAMES[slug];
  if (!frames || frames.length === 0) return null;
  return { viewBox: ART_VIEWBOX, frames };
}

/** True when we have artwork for this exercise. */
export function hasExerciseArt(exerciseId: string | null | undefined): boolean {
  return exerciseArt(exerciseId) !== null;
}
